name: Build and Sign APK

on:
  push:
    paths-ignore:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    if: contains(github.event.head_commit.message, '[build]') || contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Generate Debug Keystore
      run: |
        keytool -genkeypair -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

    - name: Sign APK with Debug Key
      run: |
        $ANDROID_HOME/build-tools/33.0.3/apksigner sign --ks debug.keystore --ks-key-alias androiddebugkey --ks-pass pass:android --key-pass pass:android app/build/outputs/apk/debug/app-debug.apk

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v1.0.${{ github.run_number }}"
        release_name: "Release v1.0.${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload Signed APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/debug/app-debug.apk
        asset_name: SkinScanner.apk
        asset_content_type: application/vnd.android.package-archive
